language: cpp

compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libboost1.48-all-dev libcurl4-openssl-dev libprotobuf-dev protobuf-compiler libdb5.1-dev libdb5.1++-dev libssl-dev libminiupnpc-dev libqrencode-dev libglib2.0-dev libglibmm-2.4-dev qt5-qmake qtbase5-dev libqt5gui5 libqt5core5 libqt5dbus5 qttools5-dev-tools python-dev
install:
 - cd src
 
script: 
 - make -f makefile.unix -j 5
 - cd ..
 - qmake -qt=qt5 USE_UPNP=- 
 - make -j 5
 

notifications:
  irc:
    channels:
      - "chat.freenode.net#neoscoin-dev"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
      - "Alt Message : %{repository_slug} - (%{commit} - %{author}): %{message}, Build Time: %{duration}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
